# Site settings
title:          Jamie Phan
description:    "My Portfolio :)."
baseurl:        ""
url:            "https://jamiephan89.github.io"

# Author
author:
  name:         Jamie Phan
  url:          https://jamiephan89.github.io
  email:        jamiephangia@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
